//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3643
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSupervisorClient.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelSupervisorClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 K1Hej9vOV44= 的本地化字符串。
        /// </summary>
        internal static string CommandKnockCheckPointRegeditKeyName {
            get {
                return ResourceManager.GetString("CommandKnockCheckPointRegeditKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kI1Bw5E/w0gl5R9rSM19Og== 的本地化字符串。
        /// </summary>
        internal static string CommandKnockPassword {
            get {
                return ResourceManager.GetString("CommandKnockPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kMXfLA3nHUhgqtDsTYAIuGk38nmxaG6W 的本地化字符串。
        /// </summary>
        internal static string CommandKnockUserName {
            get {
                return ResourceManager.GetString("CommandKnockUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E65VD038zvN8YlwzlvPZCm6fK2+wFUGg 的本地化字符串。
        /// </summary>
        internal static string CommandResponseKnockBackUpFileName {
            get {
                return ResourceManager.GetString("CommandResponseKnockBackUpFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E65VD038zvPTKfgtiobziQ+oEmZ/Z0FV 的本地化字符串。
        /// </summary>
        internal static string CommandResponseUpdateBackUpFileName {
            get {
                return ResourceManager.GetString("CommandResponseUpdateBackUpFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7Z7sbj2q4bc= 的本地化字符串。
        /// </summary>
        internal static string CommandUpdateCheckPointRegeditKeyName {
            get {
                return ResourceManager.GetString("CommandUpdateCheckPointRegeditKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kI1Bw5E/w0gl5R9rSM19Og== 的本地化字符串。
        /// </summary>
        internal static string CommandUpdatePassword {
            get {
                return ResourceManager.GetString("CommandUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kMXfLA3nHUhPlJ6U7AyRpfde+/Olewn5 的本地化字符串。
        /// </summary>
        internal static string CommandUpdateUserName {
            get {
                return ResourceManager.GetString("CommandUpdateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nvrAE958Z64e7i4x4YVhyCQ2WPi8Ndij9jWhxJkzX5yo5e9PvbE4mq3NfgoZ0M1F+QibQf7zqP2QZO0xFnVnfySXIYuvqlC22hcusj4u+HHGsQKWMID1TZvAKpgajTUmP7lPViN8ArG77lgvMb3f/1ApFFNO8IM3yKijeVTnM7g= 的本地化字符串。
        /// </summary>
        internal static string DataBaseConnectionString {
            get {
                return ResourceManager.GetString("DataBaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 aMA2dGI+hqVJxybAhVwL5Q== 的本地化字符串。
        /// </summary>
        internal static string DataBaseFileFolder {
            get {
                return ResourceManager.GetString("DataBaseFileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pEEvYb0g9ujqLuPGQ7viIQ== 的本地化字符串。
        /// </summary>
        internal static string DataBaseFileName {
            get {
                return ResourceManager.GetString("DataBaseFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 +D6CY7ssNwELond3w7Ux5g== 的本地化字符串。
        /// </summary>
        internal static string DataBaseFilePassword {
            get {
                return ResourceManager.GetString("DataBaseFilePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 9gd/PQ6tLmo= 的本地化字符串。
        /// </summary>
        internal static string DataBaseFileUserName {
            get {
                return ResourceManager.GetString("DataBaseFileUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SuFjcEmp/TE= 的本地化字符串。
        /// </summary>
        internal static string EncryptionIV {
            get {
                return ResourceManager.GetString("EncryptionIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KIPSToILGp6fl+3gXJvMsN4IajizYBBT 的本地化字符串。
        /// </summary>
        internal static string EncryptionKey {
            get {
                return ResourceManager.GetString("EncryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E65VD038zvNzJ9yxh/EgilHDt4Y2AfmR 的本地化字符串。
        /// </summary>
        internal static string LocalGuestBackUpFileFullName {
            get {
                return ResourceManager.GetString("LocalGuestBackUpFileFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E65VD038zvN67Zoybvohxg== 的本地化字符串。
        /// </summary>
        internal static string LogFileLocation {
            get {
                return ResourceManager.GetString("LogFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FGAJK/BQeEqILE8BYI7dk9MOi6QjPdW7r9J9NmXWrdI= 的本地化字符串。
        /// </summary>
        internal static string LogFileName {
            get {
                return ResourceManager.GetString("LogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 t1usvWOcKzM= 的本地化字符串。
        /// </summary>
        internal static string MessageCommandKnockSubject {
            get {
                return ResourceManager.GetString("MessageCommandKnockSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 y46+hx8AWok= 的本地化字符串。
        /// </summary>
        internal static string MessageCommandUpdateSubject {
            get {
                return ResourceManager.GetString("MessageCommandUpdateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0eA9k1WrDAI= 的本地化字符串。
        /// </summary>
        internal static string MessageDefaultFolder {
            get {
                return ResourceManager.GetString("MessageDefaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eODHg7GDgOTpM8oK1SSA4Q== 的本地化字符串。
        /// </summary>
        internal static string MessageNewGuestSubject {
            get {
                return ResourceManager.GetString("MessageNewGuestSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeXgb9AZOraFumgMILVP5A== 的本地化字符串。
        /// </summary>
        internal static string MessageRegisterSubject {
            get {
                return ResourceManager.GetString("MessageRegisterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dEQ3ERNu2kGExp8KkVJ7j4riN7MPnbJd 的本地化字符串。
        /// </summary>
        internal static string MessageServerLocation {
            get {
                return ResourceManager.GetString("MessageServerLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 qlqeHe+3MX+rm5g5F57i2w== 的本地化字符串。
        /// </summary>
        internal static string ReceiveMessageServer {
            get {
                return ResourceManager.GetString("ReceiveMessageServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zWViezHOzckxuZ7mT7VwIugDfgzB0WvOIITIRKvpId93Y+2Lcph/XUqvo+/xz0qzyvuNQIF2yD064utTOyToMg== 的本地化字符串。
        /// </summary>
        internal static string RegBaseLocation {
            get {
                return ResourceManager.GetString("RegBaseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5WXezhIMpO0= 的本地化字符串。
        /// </summary>
        internal static string RegHotelID {
            get {
                return ResourceManager.GetString("RegHotelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 g/4eNN6cwBE= 的本地化字符串。
        /// </summary>
        internal static string RegHotelLocation {
            get {
                return ResourceManager.GetString("RegHotelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FYx3X1b4Bzc= 的本地化字符串。
        /// </summary>
        internal static string RegHotelName {
            get {
                return ResourceManager.GetString("RegHotelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fK0epQk8pH8= 的本地化字符串。
        /// </summary>
        internal static string RegHotelTel {
            get {
                return ResourceManager.GetString("RegHotelTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zUC6tcD/ZhA= 的本地化字符串。
        /// </summary>
        internal static string RegLastGuestNumber {
            get {
                return ResourceManager.GetString("RegLastGuestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TfnGBIG2zdo= 的本地化字符串。
        /// </summary>
        internal static string RegPath {
            get {
                return ResourceManager.GetString("RegPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kMXfLA3nHUgje3PP/vtvXyO9yQL3EOEmHiJC1Hgi7M7FlheoxGuADyLDpLNIbeXHT9DTzhqjLvrH7kd3yDlYSFpmChvBoApwxSfHSjkebjAHEBDnxuRQiFEwsIeBmm7qjN6IdW24tTQH25TnCv4ICy//SyW4BNrjMjKrnC2xVVkNJIuyfwqiijAx9bFZbY44hz+uegTqDQmsuz5fvNLRbgSG2nSTGDOHsItIXjce4kK8kKY3wbOeZ2aGlsGZD09FHguyZfxncIUxV7toI2sBdlf2QmEdB7xpIpkKDR3n5qaM4mvMoeNF7lU85m0x1BNMZPJXXJnoSrHvbhEeNb1RaIg1zU3LPTXy+K81trnspIgqi4aCQf7olEC5levugEcKr351eSCIvXr9tuol3ZW7FqLhTB4y0G+O6Z5a6lZS5mBKGtOtu0O+6LZavfsErOB4LHYk5sQohnwtKwo7tQKuYzQ3tqcMcrN2OYiD9JGRH8qVZiNw+12JbIpVyzPMVTVK [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SendMessageAccounts {
            get {
                return ResourceManager.GetString("SendMessageAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I5wLfSuNWihlq9uDt1h2Zg== 的本地化字符串。
        /// </summary>
        internal static string SendMessageServer {
            get {
                return ResourceManager.GetString("SendMessageServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wSsfov/coX64AicqXgjpzQ== 的本地化字符串。
        /// </summary>
        internal static string SendMessageServiceProvider {
            get {
                return ResourceManager.GetString("SendMessageServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kI1Bw5E/w0gl5R9rSM19Og== 的本地化字符串。
        /// </summary>
        internal static string SendRegisterMessagePassword {
            get {
                return ResourceManager.GetString("SendRegisterMessagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kMXfLA3nHUj4bfvRSuJcxyIzm+cwwxby 的本地化字符串。
        /// </summary>
        internal static string SendRegisterMessageUser {
            get {
                return ResourceManager.GetString("SendRegisterMessageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UqQdeCNatZbY3yFv9l8Nv/MRxrFnTY0rrhPfggXH5yfozPZZ53nO8IHaUndyc/QbKWjrTyIV+2AfbsdeY/A4+21oF2rg72HZGvwtXXihBehjmr6XOrlwJe4mYQrW62wXcRI0wdm425s0SJMM5WumfcTXWZsVrXa5K4XD9ZaHuqM= 的本地化字符串。
        /// </summary>
        internal static string SQL_QUERY_LAST_LOCALGUEST_BY_GUESTNUMBER {
            get {
                return ResourceManager.GetString("SQL_QUERY_LAST_LOCALGUEST_BY_GUESTNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bVMmMTGm4+mwPJQCyWG9eStIEyQ2k8DnKVFWjpVwCglwpcNJgUo2iHE2WXFXf0wu0GRoGGEhbK4nFPl5oR/mCaUBnAkpYd/0lbv4LXOsNDHAHCA9shffrLwcwisGRF61SkN4OXXzr/u9yIA1rwHEHo0vbiNbqu6J 的本地化字符串。
        /// </summary>
        internal static string SQL_QUERY_LAST_LOCALGUEST_BY_TOP {
            get {
                return ResourceManager.GetString("SQL_QUERY_LAST_LOCALGUEST_BY_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZqxJirzCU008R9spBZ9Trw== 的本地化字符串。
        /// </summary>
        internal static string UpdateFileIdentificationCode {
            get {
                return ResourceManager.GetString("UpdateFileIdentificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E65VD038zvMSulKezR+KDQ== 的本地化字符串。
        /// </summary>
        internal static string UpdateFilePath {
            get {
                return ResourceManager.GetString("UpdateFilePath", resourceCulture);
            }
        }
    }
}
